=== mamadoujuniorsy/projet_xml/data/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="platforme">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="utilisateurs">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="utilisateur" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nom" type="xs:string"/>
                    <xs:element name="telephone" type="xs:string"/>
                    <xs:element name="email" type="xs:string" minOccurs="0"/>
                    <xs:element name="password" type="xs:string" minOccurs="0"/>
                    <xs:element name="status" type="xs:string" minOccurs="0"/>
                    <xs:element name="avatar" type="xs:string" minOccurs="0"/>
                    <xs:element name="date_creation" type="xs:dateTime" minOccurs="0"/>
                    <xs:element name="contacts" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="contact" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:attribute name="id" type="xs:string" use="required"/>
                              <xs:attribute name="date_ajout" type="xs:dateTime"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="groupes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="groupe" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nom" type="xs:string"/>
                    <xs:element name="membre" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="messages">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="message" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="expediteur" type="xs:string"/>
                    <xs:element name="destinataire" type="xs:string"/>
                    <xs:element name="contenu" type="xs:string"/>
                    <xs:element name="date" type="xs:dateTime"/>
                    <xs:element name="lu" type="xs:boolean" minOccurs="0"/>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== mamadoujuniorsy/projet_xml/data/plateforme.xml
<?xml version="1.0" encoding="UTF-8"?>
<platforme xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
  <utilisateurs>
    <utilisateur id="u1">
      <nom>Admin</nom>
      <telephone>+33 6 00 00 00 00</telephone>
      <password>$2y$10$example.hash.here</password>
      <status>En ligne</status>
      <avatar/>
      <date_creation>2025-07-28T10:00:00+00:00</date_creation>
      <contacts/>
    </utilisateur>
  <utilisateur id="u1753716703"><nom>Mamadou SY</nom><telephone>773815479</telephone><password>$2y$10$IXv2F6MbcdWa9aqcdIvjceR985y9i6l/rcsXAPoaxSIAEBDLPY57a</password><status>En ligne</status><avatar/><date_creation>2025-07-28T15:31:43+00:00</date_creation><contacts/></utilisateur><utilisateur id="u1753716787"><nom>Ousseynou</nom><telephone>770000000</telephone><password>$2y$10$jjqZEQYyleks2ZCrDQQAWehMMH56kgyHA/2Q72vcO4G/p6c3MnUGG</password><status>En ligne</status><avatar/><date_creation>2025-07-28T15:33:07+00:00</date_creation><contacts><contact id="u1753716703" date_ajout="2025-07-28T15:33:36+00:00"/></contacts></utilisateur><utilisateur id="u1753718266"><nom>Biteye</nom><telephone>781937325</telephone><password>$2y$12$.1uvvlOI2cMjRYM3ezVeTeMBh62o66sVMSdpRaSoDAHyNFeey7bP2</password><status>En ligne</status><avatar/><date_creation>2025-07-28T15:57:47+00:00</date_creation><contacts><contact id="u1753718538" date_ajout="2025-07-28T16:02:32+00:00"/><contact id="u1753722739" date_ajout="2025-07-28T17:12:37+00:00"/></contacts></utilisateur><utilisateur id="u1753718538"><nom>Diop</nom><telephone>762034181</telephone><password>$2y$12$QCA1FYbHpfv61hMtLfkaKemsR5zLOV0rQVRC0.20l14QUMeKb4eiq</password><status>En ligne</status><avatar/><date_creation>2025-07-28T16:02:18+00:00</date_creation><contacts><contact id="u1753718266" date_ajout="2025-07-28T16:05:21+00:00"/></contacts></utilisateur><utilisateur id="u1753722739"><nom>user3</nom><telephone>777777777</telephone><password>$2y$12$MApUDXCW1f/7B4K0kggjSeyb1SZy/pph3kwENv81pi9CRwbLfzUEu</password><status>En ligne</status><avatar/><date_creation>2025-07-28T17:12:19+00:00</date_creation><contacts/><blocked><blocked_user id="u1753718266" date_blocked="2025-07-29T09:07:47+00:00"/></blocked></utilisateur></utilisateurs>
  <groupes><groupe id="g1753720161"><nom>Projet</nom><membre id="u1753718538"/><membre id="u1753718266"/><membre id="u1753722739"/></groupe></groupes>
  <messages><message id="m1753716828"><expediteur>u1753716787</expediteur><destinataire>u1753716703</destinataire><contenu>salut</contenu><date>2025-07-28T15:33:48+00:00</date><lu>false</lu></message><message id="m1753718558"><expediteur>u1753718266</expediteur><destinataire>u1753718538</destinataire><contenu>Bonjour</contenu><date>2025-07-28T16:02:38+00:00</date><lu>true</lu></message><message id="m1753718730"><expediteur>u1753718538</expediteur><destinataire>u1753718266</destinataire><contenu>Salut</contenu><date>2025-07-28T16:05:30+00:00</date><lu>true</lu></message><message id="m1753720263"><expediteur>u1753718266</expediteur><destinataire>u1753718538</destinataire><contenu>ok</contenu><date>2025-07-28T16:31:03+00:00</date><lu>true</lu><type>private</type></message><message id="m1753720702"><expediteur>u1753718266</expediteur><destinataire>u1753718538</destinataire><contenu>Ca s'est bien pass√©</contenu><date>2025-07-28T16:38:22+00:00</date><lu>true</lu><type>private</type></message><message id="m1753720716"><expediteur>u1753718266</expediteur><destinataire>g1753720161</destinataire><contenu>Salut</contenu><date>2025-07-28T16:38:36+00:00</date><lu>true</lu><type>group</type></message><message id="m1753720737"><expediteur>u1753718538</expediteur><destinataire>g1753720161</destinataire><contenu>Hi</contenu><date>2025-07-28T16:38:57+00:00</date><lu>true</lu><type>group</type></message><message id="m1753722021"><expediteur>u1753718266</expediteur><destinataire>u1753718538</destinataire><contenu>ok</contenu><date>2025-07-28T17:00:21+00:00</date><lu>true</lu><type>private</type></message><message id="m1753722025"><expediteur>u1753718266</expediteur><destinataire>u1753718538</destinataire><contenu>salut</contenu><date>2025-07-28T17:00:25+00:00</date><lu>true</lu><type>private</type></message><message id="m1753722030"><expediteur>u1753718266</expediteur><destinataire>g1753720161</destinataire><contenu>hello</contenu><date>2025-07-28T17:00:30+00:00</date><lu>true</lu><type>group</type></message><message id="m1753722039"><expediteur>u1753718266</expediteur><destinataire>g1753720161</destinataire><contenu>ok ca marche</contenu><date>2025-07-28T17:00:39+00:00</date><lu>true</lu><type>group</type></message><message id="m1753722061"><expediteur>u1753718538</expediteur><destinataire>g1753720161</destinataire><contenu>je veux quitter ce groupe</contenu><date>2025-07-28T17:01:01+00:00</date><lu>true</lu><type>group</type></message><message id="m1753722392"><expediteur>u1753718266</expediteur><destinataire>g1753720161</destinataire><contenu>ok</contenu><date>2025-07-28T17:06:32+00:00</date><lu>true</lu><type>group</type></message><message id="m1753722399"><expediteur>u1753718266</expediteur><destinataire>g1753720161</destinataire><contenu>yess</contenu><date>2025-07-28T17:06:39+00:00</date><lu>true</lu><type>group</type></message><message id="m1753722689"><expediteur>u1753718538</expediteur><destinataire>u1753718266</destinataire><contenu>yesss</contenu><date>2025-07-28T17:11:29+00:00</date><lu>true</lu><type>private</type></message><message id="m1753722711"><expediteur>u1753718538</expediteur><destinataire>u1753718266</destinataire><contenu>test depuis message</contenu><date>2025-07-28T17:11:51+00:00</date><lu>true</lu><type>private</type></message><message id="m1753723197"><expediteur>u1753722739</expediteur><destinataire>g1753720161</destinataire><contenu>Salut</contenu><date>2025-07-28T17:19:57+00:00</date><lu>true</lu><type>group</type></message><message id="m1753723246"><expediteur>u1753718266</expediteur><destinataire>u1753722739</destinataire><contenu>salut user 3</contenu><date>2025-07-28T17:20:46+00:00</date><lu>false</lu><type>private</type></message><message id="m1753780140"><expediteur>u1753718266</expediteur><destinataire>g1753720161</destinataire><contenu>okk</contenu><date>2025-07-29T09:09:00+00:00</date><lu>false</lu><type>group</type></message></messages>
</platforme>
